### PR TITLE
[WIP] Docking

### PR DESCRIPTION
**Pull request by nlbuescher**
I chose `imgui-1.76` as the branch for now because that's what it's based on. If you could create a `docking` branch based on `imgui-1.76`, then I can change the branch.

Updates as discussed in #7.

### CODE REVIEW

**Comment by Dominaezzz** [comment]
I don't remember clicking `Close`. I think GitHub thought it was doing something smart when I merged the other PR.

**Comment by Dominaezzz** [comment]
I've created a `docking` branch for you to merge into.
Apart from the generated files you shouldn't have too many conflicts.

Side note:
I am considering removing the generated files from Git but I don't want contributors to worry about installing `swig`. How was your experience with swig? Was it painless to install?

**Comment by nlbuescher** [comment]
I run linux, so all I had to do was a `pacman -S swig`, and on macOS the trusty `brew install swig`, but I did have to install it. It did take me a hot minute to realize I had to run the swig and codegen tasks separately from the build task, but other than that, and the `withJava` bug, there wasn't much issue.

I think keeping the generated files is probably worth doing for the sake of some form of documentation.

**Comment by nlbuescher** [comment]
I also can't reopen the PR, might have to create a new one

**Comment by Dominaezzz** [comment]
It's because I deleted the base branch. :sweat_smile:

**Comment by nlbuescher** [comment]
Ah yes. New PR it is then. I can't change the branch, I'm finding.

**Pull request closed without merging**
